<?php
/**
 * Unit-Testing einer Zend Framework 2 Anwendung
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * Index view script
 *
 * @package    Application
 */

$this->headTitle('Page not found ');
$this->pageTitle('Page not found ');
?>
<div class="hero-unit">
    <h1>The Page could not be found!</h1>
</div>
<p class="pull-center"><a href="/" class="btn">To home page</a></p>
<hr/>
<div class="alert alert-error">
    <h2>The requested page could not be found.</h2>
    <?php
    if (isset($this->reason) && $this->reason) {
        switch ($this->reason) {
            case 'error-controller-cannot-dispatch':
                $reasonMessage = 'The requested controller was unable to process the request in a position.';
                break;
            case 'error-controller-not-found':
                $reasonMessage = 'The requested controller could be assigned to any controller class.';
                break;
            case 'error-controller-invalid':
                $reasonMessage = 'The requested controller is not accessible.';
                break;
            case 'error-router-no-match':
                $reasonMessage = 'The requested URL is no match could be found.';
                break;
            default:
                $reasonMessage = 'At this time it is not possible to determine us, why a 404 error.';
                break;
        }

        echo '<p>' . $reasonMessage . '</p>';
    }
    ?>
</div>

<div class="well">
    <h3>Further information</h3>
    <table class="table">
        <?php if (isset($this->controller) && $this->controller): ?>
            <tr>
                <th>Controller</th>
                <td><?php echo $this->escapeHtml($this->controller) ?> <?php echo (isset($this->controller_class) && $this->controller_class
                        && $this->controller_class != $this->controller) ?
                        '(' . sprintf(('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')' : ''; ?></td>
            </tr>
        <?php endif ?>
        <?php if (isset($this->exception) && $this->exception): ?>
            <tr>
                <th>Exception</th>
                <td><?php echo get_class($this->exception); ?></td>
            </tr>
            <tr>
                <th>Datei</th>
                <td>
                    <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine(
                        ) ?></pre>
                </td>
            </tr>
            <tr>
                <th>Meldung</th>
                <td>
                    <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
                </td>
            </tr>
            <tr>
                <th>Stack&nbsp;Trace</th>
                <td>
                    <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
                </td>
            </tr>
        <?php endif ?>
    </table>
</div>
