<?php
/**
 * Unit-Testing einer Zend Framework 2 Anwendung
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * Index view script
 *
 * @package    Application
 */

$this->headTitle('Server Error ');
$this->pageTitle('Server Error ');
?>
<div class="hero-unit">
    <h1>There was a server error!</h1>
</div>
<p class="pull-center"><a href="/" class="btn">To home page</a></p>
<hr/>
<div class="alert alert-error">
    <h2>There was an internal server error.</h2>
    <p>Please try again later.</p>
</div>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
    <?php if (isset($this->exception) && $this->exception instanceof Exception): ?>
        <?php $e = $this->exception->getPrevious(); ?>
        <div class="well">
            <h3>Weitere Informationen</h3>
            <table class="table">
                <tr>
                    <th>Exception</th>
                    <td><?php echo get_class($this->exception); ?></td>
                </tr>
                <tr>
                    <th>File</th>
                    <td>
                        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine(
                            ) ?></pre>
                    </td>
                </tr>
                <tr>
                    <th>Message</th>
                    <td>
                        <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
                    </td>
                </tr>
                <tr>
                    <th>Stack&nbsp;Trace</th>
                    <td>
                        <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
                    </td>
                </tr>
            </table>
        </div>
        <?php if ($e) : ?>
            <hr/>
            <div class="well">
                <h3>Previous Exceptions</h3>
                <?php while ($e) : ?>
                    <table class="table">
                        <tr>
                            <th>Exception</th>
                            <td><?php echo get_class($e); ?></td>
                        </tr>
                        <tr>
                            <th>File</th>
                            <td>
                                <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                            </td>
                        </tr>
                        <tr>
                            <th>Message</th>
                            <td>
                                <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
                            </td>
                        </tr>
                        <tr>
                            <th>Stack&nbsp;Trace</th>
                            <td>
                                <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
                            </td>
                        </tr>
                    </table>
                    <hr/>
                    <?php $e = $e->getPrevious(); ?>
                <?php endwhile; ?>
            </div>
        <?php endif; ?>
    <?php else: ?>
        <h3>No exception available</h3>
    <?php endif ?>
<?php endif ?>
