<?php
/**
 * Unit-Testing einer Zend Framework 2 Anwendung
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * Footer view script
 *
 * @package    Application
 */

$url = $this->url(null, array(), true);
?>
<footer id="footer">
    <div class="footer-top"></div>
    <div class="container">
        <div class="row-fluid">
            <div class="span4">
                <h4>Unit Testing a ZF2 Application</h4>
                <p>Using this project, you can ZF2 following track the session "Unit testing a Zend Framework application 2" again at rest on your own computer. Look at the code and try it around yourself.</p>
                <p><a href="https://plus.google.com/105130475645941839411" target="_blank">Feedback wanted!</a></p>
            </div>
            <div class="span4">
                <h4>Zend Framework Links</h4>
                <ul>
                    <li><a href="http://framework.zend.com/" target="_blank">Zend Framework Website</a></li>
                    <li><a href="http://zf2.readthedocs.org/" target="_blank">Zend Framework 2 Manual</a></li>
                    <li><a href="http://modules.zendframework.com/" target="_blank">Zend Framework 2 Module</a></li>
                    <li><a href="https://github.com/zendframework" target="_blank">Zend Framework GitHub Repository</a></li>
                    <li><a href="https://github.com/zendframework/zf2/issues" target="_blank">Zend Framework 2 Issue Tracker</a></li>
                    <li><a href="http://framework.zend.com/docs/api" target="_blank">Zend Framework API Docs</a></li>
                </ul>
            </div>
            <div class="span4">
                <h4>Other Links</h4>
                <ul>
                    <li><a href="http://www.zendframeworkschulung.de/" target="_blank">Zend Framework training</a></li>
                    <li><a href="http://www.zendframeworkbuch.de/" target="_blank">Zend Framework book</a></li>
                    <li><a href="http://www.zendframeworkmagazin.de/" target="_blank">Zend Framework Magazine</a></li>
                    <li><a href="https://plus.google.com/105130475645941839411" target="_blank">Google+ Seite Ralf Eggert</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
