<?php
/**
 * Unit-Testing einer Zend Framework 2 Anwendung
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * namespace definition and usage
 */

/**
 * Index view script
 *
 * @package    Application
 */

$this->pageTitle('Warm Welcome!');

?>
<div class="hero-unit">
    <h1>Unit Testing a ZF2 Application</h1>

    <h2>International PHP Conference 2013 in Munich</h2>
    <p>All of the examples shown in the session, are traceable using this sample project. Can be used as a basis for your own projects like it.</p>
</div>

